server:
  port: 8999
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/academy_management?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  mvc:
    static-path-pattern: /**
  resources:
      static-locations: file:C:/academy/img/

mybatis-plus:
  mapper-locations: classpath:com/demo/academymanagement/mapper/mapping/*.xml
  typeAliasesPackage: com.demo.academymanagement.modal
  configuration:
    map-underscore-to-camel-case: true
#  servlet:
#    multipart:
#      # 文件传输大小最大值设置
#      max-file-size: 2Mb
#      max-request-size: 100Mb


